FROM rust as base
RUN cargo install sccache
ENV RUSTC_WRAPPER=sccache

FROM base as build
WORKDIR "/app"
COPY Cargo.lock Cargo.lock
COPY Cargo.toml Cargo.toml
COPY src src
RUN cargo build;
RUN cargo build --release;

FROM ubuntu as debug
COPY --from=build /app/target/debug/server /usr/bin/server
CMD ["server"]

FROM ubuntu as release
COPY --from=build /app/target/release/server /usr/bin/server
CMD ["server"]
