FROM rust as base
WORKDIR "/app"
COPY Cargo.lock Cargo.lock
COPY Cargo.toml Cargo.toml
COPY src src

FROM base as build-debug
RUN cargo build; \
    cargo install --path .;

FROM base as build-release
RUN cargo build --release; \
    cargo install --path .;

FROM ubuntu as debug
COPY --from=build-debug /app/target/debug/server /usr/bin/server
CMD ["server"]

FROM ubuntu as release
COPY --from=build-release /app/target/release/server /usr/bin/server
CMD ["server"]
